### ISSUE TITLE
Checking the requirements conflicts after mockups

### ISSUE THREAD

**Issue by furknbulbul** [bounswe/bounswe2023group1#88] opened 2023-03-26 22:27 UTC
After the mockups and scenarios done by the 2-people groups, requirements will be updated. We would not want any conflict among them.

**Comment by kubraaksux** [comment] 2023-04-03 06:39
Seems like we have conflicts between them. Waiting for the opinions #105 
This problem is getting chaotic. I think its urgent even the issue is on hold.

**Comment by volcaniqueo** [comment] 2023-04-05 17:30
This issue was infeasible to complete individually since team members' opinions & approval are needed to make changes in the requirements. Available team members evaluated all the requirements in the 10th meeting. See the notes & actions items [here](https://github.com/bounswe/bounswe2023group1/wiki/Meeting-10-(04.04.2023)). I will close the issue after that action items table is completed.

**Comment by HarunErgen** [comment] 2023-04-06 02:35
I have rewritten **1.2.1 Multi-hazard support**. Needs triage.

**Comment by alperenDagi** [comment] 2023-04-08 12:15
Applied changes according to meeting 10 notes.

**Closed by alperenDagi** 2023-04-08 12:15 UTC
Labels: Priority/High, Effort/High, URGENT ❗, Revision
